import {
	AArrowDown,
	AArrowUp,
	ALargeSmall,
	Accessibility,
	Activity,
	AirVent,
	Airplay,
	AlarmClock,
	AlarmClockCheck,
	AlarmClockMinus,
	AlarmClockOff,
	AlarmClockPlus,
	AlarmSmoke,
	Album,
	AlignCenter,
	AlignCenterHorizontal,
	AlignCenterVertical,
	AlignEndHorizontal,
	AlignEndVertical,
	AlignHorizontalDistributeCenter,
	AlignHorizontalDistributeEnd,
	AlignHorizontalDistributeStart,
	AlignHorizontalJustifyCenter,
	AlignHorizontalJustifyEnd,
	AlignHorizontalJustifyStart,
	AlignHorizontalSpaceAround,
	AlignHorizontalSpaceBetween,
	AlignJustify,
	AlignLeft,
	AlignRight,
	AlignStartHorizontal,
	AlignStartVertical,
	AlignVerticalDistributeCenter,
	AlignVerticalDistributeEnd,
	AlignVerticalDistributeStart,
	AlignVerticalJustifyCenter,
	AlignVerticalJustifyEnd,
	AlignVerticalJustifyStart,
	AlignVerticalSpaceAround,
	AlignVerticalSpaceBetween,
	Ambulance,
	Ampersand,
	Ampersands,
	Amphora,
	Anchor,
	Angry,
	Annoyed,
	Antenna,
	Anvil,
	Aperture,
	AppWindow,
	AppWindowMac,
	Apple,
	Archive,
	ArchiveRestore,
	ArchiveX,
	Armchair,
	ArrowBigDown,
	ArrowBigDownDash,
	ArrowBigLeft,
	ArrowBigLeftDash,
	ArrowBigRight,
	ArrowBigRightDash,
	ArrowBigUp,
	ArrowBigUpDash,
	ArrowDown,
	ArrowDown01,
	ArrowDown10,
	ArrowDownAZ,
	ArrowDownFromLine,
	ArrowDownLeft,
	ArrowDownNarrowWide,
	ArrowDownRight,
	ArrowDownToDot,
	ArrowDownToLine,
	ArrowDownUp,
	ArrowDownWideNarrow,
	ArrowDownZA,
	ArrowLeft,
	ArrowLeftFromLine,
	ArrowLeftRight,
	ArrowLeftToLine,
	ArrowRight,
	ArrowRightFromLine,
	ArrowRightLeft,
	ArrowRightToLine,
	ArrowUp,
	ArrowUp01,
	ArrowUp10,
	ArrowUpAZ,
	ArrowUpDown,
	ArrowUpFromDot,
	ArrowUpFromLine,
	ArrowUpLeft,
	ArrowUpNarrowWide,
	ArrowUpRight,
	ArrowUpToLine,
	ArrowUpWideNarrow,
	ArrowUpZA,
	ArrowsUpFromLine,
	Asterisk,
	AtSign,
	Atom,
	AudioLines,
	AudioWaveform,
	Award,
	Axe,
	Axis3d,
	Baby,
	Backpack,
	Badge,
	BadgeAlert,
	BadgeCent,
	BadgeCheck,
	BadgeDollarSign,
	BadgeEuro,
	BadgeHelp,
	BadgeIndianRupee,
	BadgeInfo,
	BadgeJapaneseYen,
	BadgeMinus,
	BadgePercent,
	BadgePlus,
	BadgePoundSterling,
	BadgeRussianRuble,
	BadgeSwissFranc,
	BadgeX,
	BaggageClaim,
	Ban,
	Banana,
	Bandage,
	Banknote,
	Barcode,
	Baseline,
	Bath,
	Battery,
	BatteryCharging,
	BatteryFull,
	BatteryLow,
	BatteryMedium,
	BatteryPlus,
	BatteryWarning,
	Beaker,
	Bean,
	BeanOff,
	Bed,
	BedDouble,
	BedSingle,
	Beef,
	Beer,
	BeerOff,
	Bell,
	BellDot,
	BellElectric,
	BellMinus,
	BellOff,
	BellPlus,
	BellRing,
	BetweenHorizontalEnd,
	BetweenHorizontalStart,
	BetweenVerticalEnd,
	BetweenVerticalStart,
	BicepsFlexed,
	Bike,
	Binary,
	Binoculars,
	Biohazard,
	Bird,
	Bitcoin,
	Blend,
	Blinds,
	Blocks,
	Bluetooth,
	BluetoothConnected,
	BluetoothOff,
	BluetoothSearching,
	Bold,
	Bolt,
	Bomb,
	Bone,
	Book,
	BookA,
	BookAudio,
	BookCheck,
	BookCopy,
	BookDashed,
	BookDown,
	BookHeadphones,
	BookHeart,
	BookImage,
	BookKey,
	BookLock,
	BookMarked,
	BookMinus,
	BookOpen,
	BookOpenCheck,
	BookOpenText,
	BookPlus,
	BookText,
	BookType,
	BookUp,
	BookUp2,
	BookUser,
	BookX,
	Bookmark,
	BookmarkCheck,
	BookmarkMinus,
	BookmarkPlus,
	BookmarkX,
	BoomBox,
	Bot,
	BotMessageSquare,
	BotOff,
	Box,
	Boxes,
	Braces,
	Brackets,
	Brain,
	BrainCircuit,
	BrainCog,
	BrickWall,
	Briefcase,
	BriefcaseBusiness,
	BriefcaseConveyorBelt,
	BriefcaseMedical,
	BringToFront,
	Brush,
	Bug,
	BugOff,
	BugPlay,
	Building,
	Building2,
	Bus,
	BusFront,
	Cable,
	CableCar,
	Cake,
	CakeSlice,
	Calculator,
	Calendar,
	Calendar1,
	CalendarArrowDown,
	CalendarArrowUp,
	CalendarCheck,
	CalendarCheck2,
	CalendarClock,
	CalendarCog,
	CalendarDays,
	CalendarFold,
	CalendarHeart,
	CalendarMinus,
	CalendarMinus2,
	CalendarOff,
	CalendarPlus,
	CalendarPlus2,
	CalendarRange,
	CalendarSearch,
	CalendarSync,
	CalendarX,
	CalendarX2,
	Camera,
	CameraOff,
	Candy,
	CandyCane,
	CandyOff,
	Cannabis,
	Captions,
	CaptionsOff,
	Car,
	CarFront,
	CarTaxiFront,
	Caravan,
	Carrot,
	CaseLower,
	CaseSensitive,
	CaseUpper,
	CassetteTape,
	Cast,
	Castle,
	Cat,
	Cctv,
	ChartArea,
	ChartBar,
	ChartBarBig,
	ChartBarDecreasing,
	ChartBarIncreasing,
	ChartBarStacked,
	ChartCandlestick,
	ChartColumn,
	ChartColumnBig,
	ChartColumnDecreasing,
	ChartColumnIncreasing,
	ChartColumnStacked,
	ChartGantt,
	ChartLine,
	ChartNetwork,
	ChartNoAxesColumn,
	ChartNoAxesColumnDecreasing,
	ChartNoAxesColumnIncreasing,
	ChartNoAxesCombined,
	ChartNoAxesGantt,
	ChartPie,
	ChartScatter,
	ChartSpline,
	Check,
	CheckCheck,
	ChefHat,
	Cherry,
	ChevronDown,
	ChevronFirst,
	ChevronLast,
	ChevronLeft,
	ChevronRight,
	ChevronUp,
	ChevronsDown,
	ChevronsDownUp,
	ChevronsLeft,
	ChevronsLeftRight,
	ChevronsLeftRightEllipsis,
	ChevronsRight,
	ChevronsRightLeft,
	ChevronsUp,
	ChevronsUpDown,
	Chrome,
	Church,
	Cigarette,
	CigaretteOff,
	Circle,
	CircleAlert,
	CircleArrowDown,
	CircleArrowLeft,
	CircleArrowOutDownLeft,
	CircleArrowOutDownRight,
	CircleArrowOutUpLeft,
	CircleArrowOutUpRight,
	CircleArrowRight,
	CircleArrowUp,
	CircleCheck,
	CircleCheckBig,
	CircleChevronDown,
	CircleChevronLeft,
	CircleChevronRight,
	CircleChevronUp,
	CircleDashed,
	CircleDivide,
	CircleDollarSign,
	CircleDot,
	CircleDotDashed,
	CircleEllipsis,
	CircleEqual,
	CircleFadingArrowUp,
	CircleFadingPlus,
	CircleGauge,
	CircleHelp,
	CircleMinus,
	CircleOff,
	CircleParking,
	CircleParkingOff,
	CirclePause,
	CirclePercent,
	CirclePlay,
	CirclePlus,
	CirclePower,
	CircleSlash,
	CircleSlash2,
	CircleSmall,
	CircleStop,
	CircleUser,
	CircleUserRound,
	CircleX,
	CircuitBoard,
	Citrus,
	Clapperboard,
	Clipboard,
	ClipboardCheck,
	ClipboardCopy,
	ClipboardList,
	ClipboardMinus,
	ClipboardPaste,
	ClipboardPen,
	ClipboardPenLine,
	ClipboardPlus,
	ClipboardType,
	ClipboardX,
	Clock,
	Clock1,
	Clock2,
	Clock3,
	Clock4,
	Clock5,
	Clock6,
	Clock7,
	Clock8,
	Clock9,
	Clock10,
	Clock11,
	Clock12,
	ClockAlert,
	ClockArrowDown,
	ClockArrowUp,
	ClockFading,
	Cloud,
	CloudAlert,
	CloudCog,
	CloudDownload,
	CloudDrizzle,
	CloudFog,
	CloudHail,
	CloudLightning,
	CloudMoon,
	CloudMoonRain,
	CloudOff,
	CloudRain,
	CloudRainWind,
	CloudSnow,
	CloudSun,
	CloudSunRain,
	CloudUpload,
	Cloudy,
	Clover,
	Club,
	Code,
	CodeXml,
	Codepen,
	Codesandbox,
	Coffee,
	Cog,
	Coins,
	Columns2,
	Columns3,
	Columns4,
	Combine,
	Command,
	Compass,
	Component,
	Computer,
	ConciergeBell,
	Cone,
	Construction,
	Contact,
	ContactRound,
	Container,
	Contrast,
	Cookie,
	CookingPot,
	Copy,
	CopyCheck,
	CopyMinus,
	CopyPlus,
	CopySlash,
	CopyX,
	Copyleft,
	Copyright,
	CornerDownLeft,
	CornerDownRight,
	CornerLeftDown,
	CornerLeftUp,
	CornerRightDown,
	CornerRightUp,
	CornerUpLeft,
	CornerUpRight,
	Cpu,
	CreativeCommons,
	CreditCard,
	Croissant,
	Crop,
	Cross,
	Crosshair,
	Crown,
	Cuboid,
	CupSoda,
	Currency,
	Cylinder,
	Dam,
	Database,
	DatabaseBackup,
	DatabaseZap,
	Delete,
	Dessert,
	Diameter,
	Diamond,
	DiamondMinus,
	DiamondPercent,
	DiamondPlus,
	Dice1,
	Dice2,
	Dice3,
	Dice4,
	Dice5,
	Dice6,
	Dices,
	Diff,
	Disc,
	Disc2,
	Disc3,
	DiscAlbum,
	Divide,
	Dna,
	DnaOff,
	Dock,
	Dog,
	DollarSign,
	Donut,
	DoorClosed,
	DoorOpen,
	Dot,
	Download,
	DraftingCompass,
	Drama,
	Dribbble,
	Drill,
	Droplet,
	DropletOff,
	Droplets,
	Drum,
	Drumstick,
	Dumbbell,
	Ear,
	EarOff,
	Earth,
	EarthLock,
	Eclipse,
	Egg,
	EggFried,
	EggOff,
	Ellipsis,
	EllipsisVertical,
	Equal,
	EqualApproximately,
	EqualNot,
	Eraser,
	EthernetPort,
	Euro,
	Expand,
	ExternalLink,
	Eye,
	EyeClosed,
	EyeOff,
	Facebook,
	Factory,
	Fan,
	FastForward,
	Feather,
	Fence,
	FerrisWheel,
	Figma,
	File,
	FileArchive,
	FileAudio,
	FileAudio2,
	FileAxis3d,
	FileBadge,
	FileBadge2,
	FileBox,
	FileChartColumn,
	FileChartColumnIncreasing,
	FileChartLine,
	FileChartPie,
	FileCheck,
	FileCheck2,
	FileClock,
	FileCode,
	FileCode2,
	FileCog,
	FileDiff,
	FileDigit,
	FileDown,
	FileHeart,
	FileImage,
	FileInput,
	FileJson,
	FileJson2,
	FileKey,
	FileKey2,
	FileLock,
	FileLock2,
	FileMinus,
	FileMinus2,
	FileMusic,
	FileOutput,
	FilePen,
	FilePenLine,
	FilePlus,
	FilePlus2,
	FileQuestion,
	FileScan,
	FileSearch,
	FileSearch2,
	FileSliders,
	FileSpreadsheet,
	FileStack,
	FileSymlink,
	FileTerminal,
	FileText,
	FileType,
	FileType2,
	FileUp,
	FileUser,
	FileVideo,
	FileVideo2,
	FileVolume,
	FileVolume2,
	FileWarning,
	FileX,
	FileX2,
	Files,
	Film,
	Filter,
	FilterX,
	Fingerprint,
	FireExtinguisher,
	Fish,
	FishOff,
	FishSymbol,
	Flag,
	FlagOff,
	FlagTriangleLeft,
	FlagTriangleRight,
	Flame,
	FlameKindling,
	Flashlight,
	FlashlightOff,
	FlaskConical,
	FlaskConicalOff,
	FlaskRound,
	FlipHorizontal,
	FlipHorizontal2,
	FlipVertical,
	FlipVertical2,
	Flower,
	Flower2,
	Focus,
	FoldHorizontal,
	FoldVertical,
	Folder,
	FolderArchive,
	FolderCheck,
	FolderClock,
	FolderClosed,
	FolderCode,
	FolderCog,
	FolderDot,
	FolderDown,
	FolderGit,
	FolderGit2,
	FolderHeart,
	FolderInput,
	FolderKanban,
	FolderKey,
	FolderLock,
	FolderMinus,
	FolderOpen,
	FolderOpenDot,
	FolderOutput,
	FolderPen,
	FolderPlus,
	FolderRoot,
	FolderSearch,
	FolderSearch2,
	FolderSymlink,
	FolderSync,
	FolderTree,
	FolderUp,
	FolderX,
	Folders,
	Footprints,
	Forklift,
	Forward,
	Frame,
	Framer,
	Frown,
	Fuel,
	Fullscreen,
	GalleryHorizontal,
	GalleryHorizontalEnd,
	GalleryThumbnails,
	GalleryVertical,
	GalleryVerticalEnd,
	Gamepad,
	Gamepad2,
	Gauge,
	Gavel,
	Gem,
	Ghost,
	Gift,
	GitBranch,
	GitBranchPlus,
	GitCommitHorizontal,
	GitCommitVertical,
	GitCompare,
	GitCompareArrows,
	GitFork,
	GitGraph,
	GitMerge,
	GitPullRequest,
	GitPullRequestArrow,
	GitPullRequestClosed,
	GitPullRequestCreate,
	GitPullRequestCreateArrow,
	GitPullRequestDraft,
	Github,
	Gitlab,
	GlassWater,
	Glasses,
	Globe,
	GlobeLock,
	Goal,
	Grab,
	GraduationCap,
	Grape,
	Grid2x2,
	Grid2x2Check,
	Grid2x2Plus,
	Grid2x2X,
	Grid3x3,
	Grip,
	GripHorizontal,
	GripVertical,
	Group,
	Guitar,
	Ham,
	Hammer,
	Hand,
	HandCoins,
	HandHeart,
	HandHelping,
	HandMetal,
	HandPlatter,
	Handshake,
	HardDrive,
	HardDriveDownload,
	HardDriveUpload,
	HardHat,
	Hash,
	Haze,
	HdmiPort,
	Heading,
	Heading1,
	Heading2,
	Heading3,
	Heading4,
	Heading5,
	Heading6,
	HeadphoneOff,
	Headphones,
	Headset,
	Heart,
	HeartCrack,
	HeartHandshake,
	HeartOff,
	HeartPulse,
	Heater,
	Hexagon,
	Highlighter,
	History,
	Hop,
	HopOff,
	Hospital,
	Hotel,
	Hourglass,
	House,
	HousePlug,
	HousePlus,
	HouseWifi,
	IceCreamBowl,
	IceCreamCone,
	Icon,
	type IconNode,
	IdCard,
	Image,
	ImageDown,
	ImageMinus,
	ImageOff,
	ImagePlay,
	ImagePlus,
	ImageUp,
	ImageUpscale,
	Images,
	Import,
	Inbox,
	IndentDecrease,
	IndentIncrease,
	IndianRupee,
	// biome-ignore lint/suspicious/noShadowRestrictedNames: <explanation>
	Infinity,
	Info,
	InspectionPanel,
	Instagram,
	Italic,
	IterationCcw,
	IterationCw,
	JapaneseYen,
	Joystick,
	Kanban,
	Key,
	KeyRound,
	KeySquare,
	Keyboard,
	KeyboardMusic,
	KeyboardOff,
	Lamp,
	LampCeiling,
	LampDesk,
	LampFloor,
	LampWallDown,
	LampWallUp,
	LandPlot,
	Landmark,
	Languages,
	Laptop,
	LaptopMinimal,
	LaptopMinimalCheck,
	Lasso,
	LassoSelect,
	Laugh,
	Layers,
	Layers2,
	LayoutDashboard,
	LayoutGrid,
	LayoutList,
	LayoutPanelLeft,
	LayoutPanelTop,
	LayoutTemplate,
	Leaf,
	LeafyGreen,
	Lectern,
	LetterText,
	Library,
	LibraryBig,
	LifeBuoy,
	Ligature,
	Lightbulb,
	LightbulbOff,
	Link,
	Link2,
	Link2Off,
	Linkedin,
	List,
	ListCheck,
	ListChecks,
	ListCollapse,
	ListEnd,
	ListFilter,
	ListFilterPlus,
	ListMinus,
	ListMusic,
	ListOrdered,
	ListPlus,
	ListRestart,
	ListStart,
	ListTodo,
	ListTree,
	ListVideo,
	ListX,
	Loader,
	LoaderCircle,
	LoaderPinwheel,
	Locate,
	LocateFixed,
	LocateOff,
	Lock,
	LockKeyhole,
	LockKeyholeOpen,
	LockOpen,
	LogIn,
	LogOut,
	Logs,
	Lollipop,
	type LucideIcon,
	type LucideProps,
	Luggage,
	Magnet,
	Mail,
	MailCheck,
	MailMinus,
	MailOpen,
	MailPlus,
	MailQuestion,
	MailSearch,
	MailWarning,
	MailX,
	Mailbox,
	Mails,
	// biome-ignore lint/suspicious/noShadowRestrictedNames: <explanation>
	Map,
	MapPin,
	MapPinCheck,
	MapPinCheckInside,
	MapPinHouse,
	MapPinMinus,
	MapPinMinusInside,
	MapPinOff,
	MapPinPlus,
	MapPinPlusInside,
	MapPinX,
	MapPinXInside,
	MapPinned,
	MapPlus,
	Mars,
	MarsStroke,
	Martini,
	Maximize,
	Maximize2,
	Medal,
	Megaphone,
	MegaphoneOff,
	Meh,
	MemoryStick,
	Menu,
	Merge,
	MessageCircle,
	MessageCircleCode,
	MessageCircleDashed,
	MessageCircleHeart,
	MessageCircleMore,
	MessageCircleOff,
	MessageCirclePlus,
	MessageCircleQuestion,
	MessageCircleReply,
	MessageCircleWarning,
	MessageCircleX,
	MessageSquare,
	MessageSquareCode,
	MessageSquareDashed,
	MessageSquareDiff,
	MessageSquareDot,
	MessageSquareHeart,
	MessageSquareLock,
	MessageSquareMore,
	MessageSquareOff,
	MessageSquarePlus,
	MessageSquareQuote,
	MessageSquareReply,
	MessageSquareShare,
	MessageSquareText,
	MessageSquareWarning,
	MessageSquareX,
	MessagesSquare,
	Mic,
	MicOff,
	MicVocal,
	Microchip,
	Microscope,
	Microwave,
	Milestone,
	Milk,
	MilkOff,
	Minimize,
	Minimize2,
	Minus,
	Monitor,
	MonitorCheck,
	MonitorCog,
	MonitorDot,
	MonitorDown,
	MonitorOff,
	MonitorPause,
	MonitorPlay,
	MonitorSmartphone,
	MonitorSpeaker,
	MonitorStop,
	MonitorUp,
	MonitorX,
	Moon,
	MoonStar,
	Mountain,
	MountainSnow,
	Mouse,
	MouseOff,
	MousePointer,
	MousePointer2,
	MousePointerBan,
	MousePointerClick,
	Move,
	Move3d,
	MoveDiagonal,
	MoveDiagonal2,
	MoveDown,
	MoveDownLeft,
	MoveDownRight,
	MoveHorizontal,
	MoveLeft,
	MoveRight,
	MoveUp,
	MoveUpLeft,
	MoveUpRight,
	MoveVertical,
	Music,
	Music2,
	Music3,
	Music4,
	Navigation,
	Navigation2,
	Navigation2Off,
	NavigationOff,
	Network,
	Newspaper,
	Nfc,
	NonBinary,
	Notebook,
	NotebookPen,
	NotebookTabs,
	NotebookText,
	NotepadText,
	NotepadTextDashed,
	Nut,
	NutOff,
	Octagon,
	OctagonAlert,
	OctagonMinus,
	OctagonPause,
	OctagonX,
	Omega,
	Option,
	Orbit,
	Origami,
	Package,
	Package2,
	PackageCheck,
	PackageMinus,
	PackageOpen,
	PackagePlus,
	PackageSearch,
	PackageX,
	PaintBucket,
	PaintRoller,
	Paintbrush,
	PaintbrushVertical,
	Palette,
	PanelBottom,
	PanelBottomClose,
	PanelBottomDashed,
	PanelBottomOpen,
	PanelLeft,
	PanelLeftClose,
	PanelLeftDashed,
	PanelLeftOpen,
	PanelRight,
	PanelRightClose,
	PanelRightDashed,
	PanelRightOpen,
	PanelTop,
	PanelTopClose,
	PanelTopDashed,
	PanelTopOpen,
	PanelsLeftBottom,
	PanelsRightBottom,
	PanelsTopLeft,
	Paperclip,
	Parentheses,
	ParkingMeter,
	PartyPopper,
	Pause,
	PawPrint,
	PcCase,
	Pen,
	PenLine,
	PenOff,
	PenTool,
	Pencil,
	PencilLine,
	PencilOff,
	PencilRuler,
	Pentagon,
	Percent,
	PersonStanding,
	PhilippinePeso,
	Phone,
	PhoneCall,
	PhoneForwarded,
	PhoneIncoming,
	PhoneMissed,
	PhoneOff,
	PhoneOutgoing,
	Pi,
	Piano,
	Pickaxe,
	PictureInPicture,
	PictureInPicture2,
	PiggyBank,
	Pilcrow,
	PilcrowLeft,
	PilcrowRight,
	Pill,
	PillBottle,
	Pin,
	PinOff,
	Pipette,
	Pizza,
	Plane,
	PlaneLanding,
	PlaneTakeoff,
	Play,
	Plug,
	Plug2,
	PlugZap,
	Plus,
	Pocket,
	PocketKnife,
	Podcast,
	Pointer,
	PointerOff,
	Popcorn,
	Popsicle,
	PoundSterling,
	Power,
	PowerOff,
	Presentation,
	Printer,
	PrinterCheck,
	Projector,
	Proportions,
	Puzzle,
	Pyramid,
	QrCode,
	Quote,
	Rabbit,
	Radar,
	Radiation,
	Radical,
	Radio,
	RadioReceiver,
	RadioTower,
	Radius,
	RailSymbol,
	Rainbow,
	Rat,
	Ratio,
	Receipt,
	ReceiptCent,
	ReceiptEuro,
	ReceiptIndianRupee,
	ReceiptJapaneseYen,
	ReceiptPoundSterling,
	ReceiptRussianRuble,
	ReceiptSwissFranc,
	ReceiptText,
	RectangleEllipsis,
	RectangleHorizontal,
	RectangleVertical,
	Recycle,
	Redo,
	Redo2,
	RedoDot,
	RefreshCcw,
	RefreshCcwDot,
	RefreshCw,
	RefreshCwOff,
	Refrigerator,
	Regex,
	RemoveFormatting,
	Repeat,
	Repeat1,
	Repeat2,
	Replace,
	ReplaceAll,
	Reply,
	ReplyAll,
	Rewind,
	Ribbon,
	Rocket,
	RockingChair,
	RollerCoaster,
	Rotate3d,
	RotateCcw,
	RotateCcwSquare,
	RotateCw,
	RotateCwSquare,
	Route,
	RouteOff,
	Router,
	Rows2,
	Rows3,
	Rows4,
	Rss,
	Ruler,
	RussianRuble,
	Sailboat,
	Salad,
	Sandwich,
	Satellite,
	SatelliteDish,
	SaudiRiyal,
	Save,
	SaveAll,
	SaveOff,
	Scale,
	Scale3d,
	Scaling,
	Scan,
	ScanBarcode,
	ScanEye,
	ScanFace,
	ScanHeart,
	ScanLine,
	ScanQrCode,
	ScanSearch,
	ScanText,
	School,
	Scissors,
	ScissorsLineDashed,
	ScreenShare,
	ScreenShareOff,
	Scroll,
	ScrollText,
	Search,
	SearchCheck,
	SearchCode,
	SearchSlash,
	SearchX,
	Section,
	Send,
	SendHorizontal,
	SendToBack,
	SeparatorHorizontal,
	SeparatorVertical,
	Server,
	ServerCog,
	ServerCrash,
	ServerOff,
	Settings,
	Settings2,
	Shapes,
	Share,
	Share2,
	Sheet,
	Shell,
	Shield,
	ShieldAlert,
	ShieldBan,
	ShieldCheck,
	ShieldEllipsis,
	ShieldHalf,
	ShieldMinus,
	ShieldOff,
	ShieldPlus,
	ShieldQuestion,
	ShieldUser,
	ShieldX,
	Ship,
	ShipWheel,
	Shirt,
	ShoppingBag,
	ShoppingBasket,
	ShoppingCart,
	Shovel,
	ShowerHead,
	Shrimp,
	Shrink,
	Shrub,
	Shuffle,
	Sigma,
	Signal,
	SignalHigh,
	SignalLow,
	SignalMedium,
	SignalZero,
	Signature,
	Signpost,
	SignpostBig,
	Siren,
	SkipBack,
	SkipForward,
	Skull,
	Slack,
	Slash,
	Slice,
	SlidersHorizontal,
	SlidersVertical,
	Smartphone,
	SmartphoneCharging,
	SmartphoneNfc,
	Smile,
	SmilePlus,
	Snail,
	Snowflake,
	Sofa,
	Soup,
	Space,
	Spade,
	Sparkle,
	Sparkles,
	Speaker,
	Speech,
	SpellCheck,
	SpellCheck2,
	Spline,
	Split,
	SprayCan,
	Sprout,
	Square,
	SquareActivity,
	SquareArrowDown,
	SquareArrowDownLeft,
	SquareArrowDownRight,
	SquareArrowLeft,
	SquareArrowOutDownLeft,
	SquareArrowOutDownRight,
	SquareArrowOutUpLeft,
	SquareArrowOutUpRight,
	SquareArrowRight,
	SquareArrowUp,
	SquareArrowUpLeft,
	SquareArrowUpRight,
	SquareAsterisk,
	SquareBottomDashedScissors,
	SquareChartGantt,
	SquareCheck,
	SquareCheckBig,
	SquareChevronDown,
	SquareChevronLeft,
	SquareChevronRight,
	SquareChevronUp,
	SquareCode,
	SquareDashed,
	SquareDashedBottom,
	SquareDashedBottomCode,
	SquareDashedKanban,
	SquareDashedMousePointer,
	SquareDivide,
	SquareDot,
	SquareEqual,
	SquareFunction,
	SquareKanban,
	SquareLibrary,
	SquareM,
	SquareMenu,
	SquareMinus,
	SquareMousePointer,
	SquareParking,
	SquareParkingOff,
	SquarePen,
	SquarePercent,
	SquarePi,
	SquarePilcrow,
	SquarePlay,
	SquarePlus,
	SquarePower,
	SquareRadical,
	SquareRoundCorner,
	SquareScissors,
	SquareSigma,
	SquareSlash,
	SquareSplitHorizontal,
	SquareSplitVertical,
	SquareSquare,
	SquareStack,
	SquareTerminal,
	SquareUser,
	SquareUserRound,
	SquareX,
	Squircle,
	Squirrel,
	Stamp,
	Star,
	StarHalf,
	StarOff,
	StepBack,
	StepForward,
	Stethoscope,
	Sticker,
	StickyNote,
	Store,
	StretchHorizontal,
	StretchVertical,
	Strikethrough,
	Subscript,
	Sun,
	SunDim,
	SunMedium,
	SunMoon,
	SunSnow,
	Sunrise,
	Sunset,
	Superscript,
	SwatchBook,
	SwissFranc,
	SwitchCamera,
	Sword,
	Swords,
	Syringe,
	Table,
	Table2,
	TableCellsMerge,
	TableCellsSplit,
	TableColumnsSplit,
	TableOfContents,
	TableProperties,
	TableRowsSplit,
	Tablet,
	TabletSmartphone,
	Tablets,
	Tag,
	Tags,
	Tally1,
	Tally2,
	Tally3,
	Tally4,
	Tally5,
	Tangent,
	Target,
	Telescope,
	Tent,
	TentTree,
	Terminal,
	TestTube,
	TestTubeDiagonal,
	TestTubes,
	Text,
	TextCursor,
	TextCursorInput,
	TextQuote,
	TextSearch,
	TextSelect,
	Theater,
	Thermometer,
	ThermometerSnowflake,
	ThermometerSun,
	ThumbsDown,
	ThumbsUp,
	Ticket,
	TicketCheck,
	TicketMinus,
	TicketPercent,
	TicketPlus,
	TicketSlash,
	TicketX,
	Tickets,
	TicketsPlane,
	Timer,
	TimerOff,
	TimerReset,
	ToggleLeft,
	ToggleRight,
	Toilet,
	Tornado,
	Torus,
	Touchpad,
	TouchpadOff,
	TowerControl,
	ToyBrick,
	Tractor,
	TrafficCone,
	TrainFront,
	TrainFrontTunnel,
	TrainTrack,
	TramFront,
	Transgender,
	Trash,
	Trash2,
	TreeDeciduous,
	TreePalm,
	TreePine,
	Trees,
	Trello,
	TrendingDown,
	TrendingUp,
	TrendingUpDown,
	Triangle,
	TriangleAlert,
	TriangleDashed,
	TriangleRight,
	Trophy,
	Truck,
	Turtle,
	Tv,
	TvMinimal,
	TvMinimalPlay,
	Twitch,
	Twitter,
	Type,
	TypeOutline,
	Umbrella,
	UmbrellaOff,
	Underline,
	Undo,
	Undo2,
	UndoDot,
	UnfoldHorizontal,
	UnfoldVertical,
	Ungroup,
	University,
	Unlink,
	Unlink2,
	Unplug,
	Upload,
	Usb,
	User,
	UserCheck,
	UserCog,
	UserMinus,
	UserPen,
	UserPlus,
	UserRound,
	UserRoundCheck,
	UserRoundCog,
	UserRoundMinus,
	UserRoundPen,
	UserRoundPlus,
	UserRoundSearch,
	UserRoundX,
	UserSearch,
	UserX,
	Users,
	UsersRound,
	Utensils,
	UtensilsCrossed,
	UtilityPole,
	Variable,
	Vault,
	Vegan,
	VenetianMask,
	Venus,
	VenusAndMars,
	Vibrate,
	VibrateOff,
	Video,
	VideoOff,
	Videotape,
	View,
	Voicemail,
	Volleyball,
	Volume,
	Volume1,
	Volume2,
	VolumeOff,
	VolumeX,
	Vote,
	Wallet,
	WalletCards,
	WalletMinimal,
	Wallpaper,
	Wand,
	WandSparkles,
	Warehouse,
	WashingMachine,
	Watch,
	Waves,
	WavesLadder,
	Waypoints,
	Webcam,
	Webhook,
	WebhookOff,
	Weight,
	Wheat,
	WheatOff,
	WholeWord,
	Wifi,
	WifiHigh,
	WifiLow,
	WifiOff,
	WifiZero,
	Wind,
	WindArrowDown,
	Wine,
	WineOff,
	Workflow,
	Worm,
	WrapText,
	Wrench,
	X,
	Youtube,
	Zap,
	ZapOff,
	ZoomIn,
	ZoomOut,
	createLucideIcon,
} from "lucide-react-native";
import { cssInterop } from "nativewind";

export function iconWithClassName(icon: LucideIcon) {
	cssInterop(icon, {
		className: {
			target: "style",
			nativeStyleToProp: {
				color: true,
				opacity: true,
			},
		},
	});
}

export function initIconWithClassName() {
	iconWithClassName(AArrowDown);
	iconWithClassName(AArrowUp);
	iconWithClassName(ALargeSmall);
	iconWithClassName(Accessibility);
	iconWithClassName(Activity);
	iconWithClassName(AirVent);
	iconWithClassName(Airplay);
	iconWithClassName(AlarmClock);
	iconWithClassName(AlarmClockCheck);
	iconWithClassName(AlarmClockMinus);
	iconWithClassName(AlarmClockOff);
	iconWithClassName(AlarmClockPlus);
	iconWithClassName(AlarmSmoke);
	iconWithClassName(Album);
	iconWithClassName(AlignCenter);
	iconWithClassName(AlignCenterHorizontal);
	iconWithClassName(AlignCenterVertical);
	iconWithClassName(AlignEndHorizontal);
	iconWithClassName(AlignEndVertical);
	iconWithClassName(AlignHorizontalDistributeCenter);
	iconWithClassName(AlignHorizontalDistributeEnd);
	iconWithClassName(AlignHorizontalDistributeStart);
	iconWithClassName(AlignHorizontalJustifyCenter);
	iconWithClassName(AlignHorizontalJustifyEnd);
	iconWithClassName(AlignHorizontalJustifyStart);
	iconWithClassName(AlignHorizontalSpaceAround);
	iconWithClassName(AlignHorizontalSpaceBetween);
	iconWithClassName(AlignJustify);
	iconWithClassName(AlignLeft);
	iconWithClassName(AlignRight);
	iconWithClassName(AlignStartHorizontal);
	iconWithClassName(AlignStartVertical);
	iconWithClassName(AlignVerticalDistributeCenter);
	iconWithClassName(AlignVerticalDistributeEnd);
	iconWithClassName(AlignVerticalDistributeStart);
	iconWithClassName(AlignVerticalJustifyCenter);
	iconWithClassName(AlignVerticalJustifyEnd);
	iconWithClassName(AlignVerticalJustifyStart);
	iconWithClassName(AlignVerticalSpaceAround);
	iconWithClassName(AlignVerticalSpaceBetween);
	iconWithClassName(Ambulance);
	iconWithClassName(Ampersand);
	iconWithClassName(Ampersands);
	iconWithClassName(Amphora);
	iconWithClassName(Anchor);
	iconWithClassName(Angry);
	iconWithClassName(Annoyed);
	iconWithClassName(Antenna);
	iconWithClassName(Anvil);
	iconWithClassName(Aperture);
	iconWithClassName(AppWindow);
	iconWithClassName(AppWindowMac);
	iconWithClassName(Apple);
	iconWithClassName(Archive);
	iconWithClassName(ArchiveRestore);
	iconWithClassName(ArchiveX);
	iconWithClassName(Armchair);
	iconWithClassName(ArrowBigDown);
	iconWithClassName(ArrowBigDownDash);
	iconWithClassName(ArrowBigLeft);
	iconWithClassName(ArrowBigLeftDash);
	iconWithClassName(ArrowBigRight);
	iconWithClassName(ArrowBigRightDash);
	iconWithClassName(ArrowBigUp);
	iconWithClassName(ArrowBigUpDash);
	iconWithClassName(ArrowDown);
	iconWithClassName(ArrowDown01);
	iconWithClassName(ArrowDown10);
	iconWithClassName(ArrowDownAZ);
	iconWithClassName(ArrowDownFromLine);
	iconWithClassName(ArrowDownLeft);
	iconWithClassName(ArrowDownNarrowWide);
	iconWithClassName(ArrowDownRight);
	iconWithClassName(ArrowDownToDot);
	iconWithClassName(ArrowDownToLine);
	iconWithClassName(ArrowDownUp);
	iconWithClassName(ArrowDownWideNarrow);
	iconWithClassName(ArrowDownZA);
	iconWithClassName(ArrowLeft);
	iconWithClassName(ArrowLeftFromLine);
	iconWithClassName(ArrowLeftRight);
	iconWithClassName(ArrowLeftToLine);
	iconWithClassName(ArrowRight);
	iconWithClassName(ArrowRightFromLine);
	iconWithClassName(ArrowRightLeft);
	iconWithClassName(ArrowRightToLine);
	iconWithClassName(ArrowUp);
	iconWithClassName(ArrowUp01);
	iconWithClassName(ArrowUp10);
	iconWithClassName(ArrowUpAZ);
	iconWithClassName(ArrowUpDown);
	iconWithClassName(ArrowUpFromDot);
	iconWithClassName(ArrowUpFromLine);
	iconWithClassName(ArrowUpLeft);
	iconWithClassName(ArrowUpNarrowWide);
	iconWithClassName(ArrowUpRight);
	iconWithClassName(ArrowUpToLine);
	iconWithClassName(ArrowUpWideNarrow);
	iconWithClassName(ArrowUpZA);
	iconWithClassName(ArrowsUpFromLine);
	iconWithClassName(Asterisk);
	iconWithClassName(AtSign);
	iconWithClassName(Atom);
	iconWithClassName(AudioLines);
	iconWithClassName(AudioWaveform);
	iconWithClassName(Award);
	iconWithClassName(Axe);
	iconWithClassName(Axis3d);
	iconWithClassName(Baby);
	iconWithClassName(Backpack);
	iconWithClassName(Badge);
	iconWithClassName(BadgeAlert);
	iconWithClassName(BadgeCent);
	iconWithClassName(BadgeCheck);
	iconWithClassName(BadgeDollarSign);
	iconWithClassName(BadgeEuro);
	iconWithClassName(BadgeHelp);
	iconWithClassName(BadgeIndianRupee);
	iconWithClassName(BadgeInfo);
	iconWithClassName(BadgeJapaneseYen);
	iconWithClassName(BadgeMinus);
	iconWithClassName(BadgePercent);
	iconWithClassName(BadgePlus);
	iconWithClassName(BadgePoundSterling);
	iconWithClassName(BadgeRussianRuble);
	iconWithClassName(BadgeSwissFranc);
	iconWithClassName(BadgeX);
	iconWithClassName(BaggageClaim);
	iconWithClassName(Ban);
	iconWithClassName(Banana);
	iconWithClassName(Bandage);
	iconWithClassName(Banknote);
	iconWithClassName(Barcode);
	iconWithClassName(Baseline);
	iconWithClassName(Bath);
	iconWithClassName(Battery);
	iconWithClassName(BatteryCharging);
	iconWithClassName(BatteryFull);
	iconWithClassName(BatteryLow);
	iconWithClassName(BatteryMedium);
	iconWithClassName(BatteryPlus);
	iconWithClassName(BatteryWarning);
	iconWithClassName(Beaker);
	iconWithClassName(Bean);
	iconWithClassName(BeanOff);
	iconWithClassName(Bed);
	iconWithClassName(BedDouble);
	iconWithClassName(BedSingle);
	iconWithClassName(Beef);
	iconWithClassName(Beer);
	iconWithClassName(BeerOff);
	iconWithClassName(Bell);
	iconWithClassName(BellDot);
	iconWithClassName(BellElectric);
	iconWithClassName(BellMinus);
	iconWithClassName(BellOff);
	iconWithClassName(BellPlus);
	iconWithClassName(BellRing);
	iconWithClassName(BetweenHorizontalEnd);
	iconWithClassName(BetweenHorizontalStart);
	iconWithClassName(BetweenVerticalEnd);
	iconWithClassName(BetweenVerticalStart);
	iconWithClassName(BicepsFlexed);
	iconWithClassName(Bike);
	iconWithClassName(Binary);
	iconWithClassName(Binoculars);
	iconWithClassName(Biohazard);
	iconWithClassName(Bird);
	iconWithClassName(Bitcoin);
	iconWithClassName(Blend);
	iconWithClassName(Blinds);
	iconWithClassName(Blocks);
	iconWithClassName(Bluetooth);
	iconWithClassName(BluetoothConnected);
	iconWithClassName(BluetoothOff);
	iconWithClassName(BluetoothSearching);
	iconWithClassName(Bold);
	iconWithClassName(Bolt);
	iconWithClassName(Bomb);
	iconWithClassName(Bone);
	iconWithClassName(Book);
	iconWithClassName(BookA);
	iconWithClassName(BookAudio);
	iconWithClassName(BookCheck);
	iconWithClassName(BookCopy);
	iconWithClassName(BookDashed);
	iconWithClassName(BookDown);
	iconWithClassName(BookHeadphones);
	iconWithClassName(BookHeart);
	iconWithClassName(BookImage);
	iconWithClassName(BookKey);
	iconWithClassName(BookLock);
	iconWithClassName(BookMarked);
	iconWithClassName(BookMinus);
	iconWithClassName(BookOpen);
	iconWithClassName(BookOpenCheck);
	iconWithClassName(BookOpenText);
	iconWithClassName(BookPlus);
	iconWithClassName(BookText);
	iconWithClassName(BookType);
	iconWithClassName(BookUp);
	iconWithClassName(BookUp2);
	iconWithClassName(BookUser);
	iconWithClassName(BookX);
	iconWithClassName(Bookmark);
	iconWithClassName(BookmarkCheck);
	iconWithClassName(BookmarkMinus);
	iconWithClassName(BookmarkPlus);
	iconWithClassName(BookmarkX);
	iconWithClassName(BoomBox);
	iconWithClassName(Bot);
	iconWithClassName(BotMessageSquare);
	iconWithClassName(BotOff);
	iconWithClassName(Box);
	iconWithClassName(Boxes);
	iconWithClassName(Braces);
	iconWithClassName(Brackets);
	iconWithClassName(Brain);
	iconWithClassName(BrainCircuit);
	iconWithClassName(BrainCog);
	iconWithClassName(BrickWall);
	iconWithClassName(Briefcase);
	iconWithClassName(BriefcaseBusiness);
	iconWithClassName(BriefcaseConveyorBelt);
	iconWithClassName(BriefcaseMedical);
	iconWithClassName(BringToFront);
	iconWithClassName(Brush);
	iconWithClassName(Bug);
	iconWithClassName(BugOff);
	iconWithClassName(BugPlay);
	iconWithClassName(Building);
	iconWithClassName(Building2);
	iconWithClassName(Bus);
	iconWithClassName(BusFront);
	iconWithClassName(Cable);
	iconWithClassName(CableCar);
	iconWithClassName(Cake);
	iconWithClassName(CakeSlice);
	iconWithClassName(Calculator);
	iconWithClassName(Calendar);
	iconWithClassName(Calendar1);
	iconWithClassName(CalendarArrowDown);
	iconWithClassName(CalendarArrowUp);
	iconWithClassName(CalendarCheck);
	iconWithClassName(CalendarCheck2);
	iconWithClassName(CalendarClock);
	iconWithClassName(CalendarCog);
	iconWithClassName(CalendarDays);
	iconWithClassName(CalendarFold);
	iconWithClassName(CalendarHeart);
	iconWithClassName(CalendarMinus);
	iconWithClassName(CalendarMinus2);
	iconWithClassName(CalendarOff);
	iconWithClassName(CalendarPlus);
	iconWithClassName(CalendarPlus2);
	iconWithClassName(CalendarRange);
	iconWithClassName(CalendarSearch);
	iconWithClassName(CalendarSync);
	iconWithClassName(CalendarX);
	iconWithClassName(CalendarX2);
	iconWithClassName(Camera);
	iconWithClassName(CameraOff);
	iconWithClassName(Candy);
	iconWithClassName(CandyCane);
	iconWithClassName(CandyOff);
	iconWithClassName(Cannabis);
	iconWithClassName(Captions);
	iconWithClassName(CaptionsOff);
	iconWithClassName(Car);
	iconWithClassName(CarFront);
	iconWithClassName(CarTaxiFront);
	iconWithClassName(Caravan);
	iconWithClassName(Carrot);
	iconWithClassName(CaseLower);
	iconWithClassName(CaseSensitive);
	iconWithClassName(CaseUpper);
	iconWithClassName(CassetteTape);
	iconWithClassName(Cast);
	iconWithClassName(Castle);
	iconWithClassName(Cat);
	iconWithClassName(Cctv);
	iconWithClassName(ChartArea);
	iconWithClassName(ChartBar);
	iconWithClassName(ChartBarBig);
	iconWithClassName(ChartBarDecreasing);
	iconWithClassName(ChartBarIncreasing);
	iconWithClassName(ChartBarStacked);
	iconWithClassName(ChartCandlestick);
	iconWithClassName(ChartColumn);
	iconWithClassName(ChartColumnBig);
	iconWithClassName(ChartColumnDecreasing);
	iconWithClassName(ChartColumnIncreasing);
	iconWithClassName(ChartColumnStacked);
	iconWithClassName(ChartGantt);
	iconWithClassName(ChartLine);
	iconWithClassName(ChartNetwork);
	iconWithClassName(ChartNoAxesColumn);
	iconWithClassName(ChartNoAxesColumnDecreasing);
	iconWithClassName(ChartNoAxesColumnIncreasing);
	iconWithClassName(ChartNoAxesCombined);
	iconWithClassName(ChartNoAxesGantt);
	iconWithClassName(ChartPie);
	iconWithClassName(ChartScatter);
	iconWithClassName(ChartSpline);
	iconWithClassName(Check);
	iconWithClassName(CheckCheck);
	iconWithClassName(ChefHat);
	iconWithClassName(Cherry);
	iconWithClassName(ChevronDown);
	iconWithClassName(ChevronFirst);
	iconWithClassName(ChevronLast);
	iconWithClassName(ChevronLeft);
	iconWithClassName(ChevronRight);
	iconWithClassName(ChevronUp);
	iconWithClassName(ChevronsDown);
	iconWithClassName(ChevronsDownUp);
	iconWithClassName(ChevronsLeft);
	iconWithClassName(ChevronsLeftRight);
	iconWithClassName(ChevronsLeftRightEllipsis);
	iconWithClassName(ChevronsRight);
	iconWithClassName(ChevronsRightLeft);
	iconWithClassName(ChevronsUp);
	iconWithClassName(ChevronsUpDown);
	iconWithClassName(Chrome);
	iconWithClassName(Church);
	iconWithClassName(Cigarette);
	iconWithClassName(CigaretteOff);
	iconWithClassName(Circle);
	iconWithClassName(CircleAlert);
	iconWithClassName(CircleArrowDown);
	iconWithClassName(CircleArrowLeft);
	iconWithClassName(CircleArrowOutDownLeft);
	iconWithClassName(CircleArrowOutDownRight);
	iconWithClassName(CircleArrowOutUpLeft);
	iconWithClassName(CircleArrowOutUpRight);
	iconWithClassName(CircleArrowRight);
	iconWithClassName(CircleArrowUp);
	iconWithClassName(CircleCheck);
	iconWithClassName(CircleCheckBig);
	iconWithClassName(CircleChevronDown);
	iconWithClassName(CircleChevronLeft);
	iconWithClassName(CircleChevronRight);
	iconWithClassName(CircleChevronUp);
	iconWithClassName(CircleDashed);
	iconWithClassName(CircleDivide);
	iconWithClassName(CircleDollarSign);
	iconWithClassName(CircleDot);
	iconWithClassName(CircleDotDashed);
	iconWithClassName(CircleEllipsis);
	iconWithClassName(CircleEqual);
	iconWithClassName(CircleFadingArrowUp);
	iconWithClassName(CircleFadingPlus);
	iconWithClassName(CircleGauge);
	iconWithClassName(CircleHelp);
	iconWithClassName(CircleMinus);
	iconWithClassName(CircleOff);
	iconWithClassName(CircleParking);
	iconWithClassName(CircleParkingOff);
	iconWithClassName(CirclePause);
	iconWithClassName(CirclePercent);
	iconWithClassName(CirclePlay);
	iconWithClassName(CirclePlus);
	iconWithClassName(CirclePower);
	iconWithClassName(CircleSlash);
	iconWithClassName(CircleSlash2);
	iconWithClassName(CircleSmall);
	iconWithClassName(CircleStop);
	iconWithClassName(CircleUser);
	iconWithClassName(CircleUserRound);
	iconWithClassName(CircleX);
	iconWithClassName(CircuitBoard);
	iconWithClassName(Citrus);
	iconWithClassName(Clapperboard);
	iconWithClassName(Clipboard);
	iconWithClassName(ClipboardCheck);
	iconWithClassName(ClipboardCopy);
	iconWithClassName(ClipboardList);
	iconWithClassName(ClipboardMinus);
	iconWithClassName(ClipboardPaste);
	iconWithClassName(ClipboardPen);
	iconWithClassName(ClipboardPenLine);
	iconWithClassName(ClipboardPlus);
	iconWithClassName(ClipboardType);
	iconWithClassName(ClipboardX);
	iconWithClassName(Clock);
	iconWithClassName(Clock1);
	iconWithClassName(Clock10);
	iconWithClassName(Clock11);
	iconWithClassName(Clock12);
	iconWithClassName(Clock2);
	iconWithClassName(Clock3);
	iconWithClassName(Clock4);
	iconWithClassName(Clock5);
	iconWithClassName(Clock6);
	iconWithClassName(Clock7);
	iconWithClassName(Clock8);
	iconWithClassName(Clock9);
	iconWithClassName(ClockAlert);
	iconWithClassName(ClockArrowDown);
	iconWithClassName(ClockArrowUp);
	iconWithClassName(ClockFading);
	iconWithClassName(Cloud);
	iconWithClassName(CloudAlert);
	iconWithClassName(CloudCog);
	iconWithClassName(CloudDownload);
	iconWithClassName(CloudDrizzle);
	iconWithClassName(CloudFog);
	iconWithClassName(CloudHail);
	iconWithClassName(CloudLightning);
	iconWithClassName(CloudMoon);
	iconWithClassName(CloudMoonRain);
	iconWithClassName(CloudOff);
	iconWithClassName(CloudRain);
	iconWithClassName(CloudRainWind);
	iconWithClassName(CloudSnow);
	iconWithClassName(CloudSun);
	iconWithClassName(CloudSunRain);
	iconWithClassName(CloudUpload);
	iconWithClassName(Cloudy);
	iconWithClassName(Clover);
	iconWithClassName(Club);
	iconWithClassName(Code);
	iconWithClassName(CodeXml);
	iconWithClassName(Codepen);
	iconWithClassName(Codesandbox);
	iconWithClassName(Coffee);
	iconWithClassName(Cog);
	iconWithClassName(Coins);
	iconWithClassName(Columns2);
	iconWithClassName(Columns3);
	iconWithClassName(Columns4);
	iconWithClassName(Combine);
	iconWithClassName(Command);
	iconWithClassName(Compass);
	iconWithClassName(Component);
	iconWithClassName(Computer);
	iconWithClassName(ConciergeBell);
	iconWithClassName(Cone);
	iconWithClassName(Construction);
	iconWithClassName(Contact);
	iconWithClassName(ContactRound);
	iconWithClassName(Container);
	iconWithClassName(Contrast);
	iconWithClassName(Cookie);
	iconWithClassName(CookingPot);
	iconWithClassName(Copy);
	iconWithClassName(CopyCheck);
	iconWithClassName(CopyMinus);
	iconWithClassName(CopyPlus);
	iconWithClassName(CopySlash);
	iconWithClassName(CopyX);
	iconWithClassName(Copyleft);
	iconWithClassName(Copyright);
	iconWithClassName(CornerDownLeft);
	iconWithClassName(CornerDownRight);
	iconWithClassName(CornerLeftDown);
	iconWithClassName(CornerLeftUp);
	iconWithClassName(CornerRightDown);
	iconWithClassName(CornerRightUp);
	iconWithClassName(CornerUpLeft);
	iconWithClassName(CornerUpRight);
	iconWithClassName(Cpu);
	iconWithClassName(CreativeCommons);
	iconWithClassName(CreditCard);
	iconWithClassName(Croissant);
	iconWithClassName(Crop);
	iconWithClassName(Cross);
	iconWithClassName(Crosshair);
	iconWithClassName(Crown);
	iconWithClassName(Cuboid);
	iconWithClassName(CupSoda);
	iconWithClassName(Currency);
	iconWithClassName(Cylinder);
	iconWithClassName(Dam);
	iconWithClassName(Database);
	iconWithClassName(DatabaseBackup);
	iconWithClassName(DatabaseZap);
	iconWithClassName(Delete);
	iconWithClassName(Dessert);
	iconWithClassName(Diameter);
	iconWithClassName(Diamond);
	iconWithClassName(DiamondMinus);
	iconWithClassName(DiamondPercent);
	iconWithClassName(DiamondPlus);
	iconWithClassName(Dice1);
	iconWithClassName(Dice2);
	iconWithClassName(Dice3);
	iconWithClassName(Dice4);
	iconWithClassName(Dice5);
	iconWithClassName(Dice6);
	iconWithClassName(Dices);
	iconWithClassName(Diff);
	iconWithClassName(Disc);
	iconWithClassName(Disc2);
	iconWithClassName(Disc3);
	iconWithClassName(DiscAlbum);
	iconWithClassName(Divide);
	iconWithClassName(Dna);
	iconWithClassName(DnaOff);
	iconWithClassName(Dock);
	iconWithClassName(Dog);
	iconWithClassName(DollarSign);
	iconWithClassName(Donut);
	iconWithClassName(DoorClosed);
	iconWithClassName(DoorOpen);
	iconWithClassName(Dot);
	iconWithClassName(Download);
	iconWithClassName(DraftingCompass);
	iconWithClassName(Drama);
	iconWithClassName(Dribbble);
	iconWithClassName(Drill);
	iconWithClassName(Droplet);
	iconWithClassName(DropletOff);
	iconWithClassName(Droplets);
	iconWithClassName(Drum);
	iconWithClassName(Drumstick);
	iconWithClassName(Dumbbell);
	iconWithClassName(Ear);
	iconWithClassName(EarOff);
	iconWithClassName(Earth);
	iconWithClassName(EarthLock);
	iconWithClassName(Eclipse);
	iconWithClassName(Egg);
	iconWithClassName(EggFried);
	iconWithClassName(EggOff);
	iconWithClassName(Ellipsis);
	iconWithClassName(EllipsisVertical);
	iconWithClassName(Equal);
	iconWithClassName(EqualApproximately);
	iconWithClassName(EqualNot);
	iconWithClassName(Eraser);
	iconWithClassName(EthernetPort);
	iconWithClassName(Euro);
	iconWithClassName(Expand);
	iconWithClassName(ExternalLink);
	iconWithClassName(Eye);
	iconWithClassName(EyeClosed);
	iconWithClassName(EyeOff);
	iconWithClassName(Facebook);
	iconWithClassName(Factory);
	iconWithClassName(Fan);
	iconWithClassName(FastForward);
	iconWithClassName(Feather);
	iconWithClassName(Fence);
	iconWithClassName(FerrisWheel);
	iconWithClassName(Figma);
	iconWithClassName(File);
	iconWithClassName(FileArchive);
	iconWithClassName(FileAudio);
	iconWithClassName(FileAudio2);
	iconWithClassName(FileAxis3d);
	iconWithClassName(FileBadge);
	iconWithClassName(FileBadge2);
	iconWithClassName(FileBox);
	iconWithClassName(FileChartColumn);
	iconWithClassName(FileChartColumnIncreasing);
	iconWithClassName(FileChartLine);
	iconWithClassName(FileChartPie);
	iconWithClassName(FileCheck);
	iconWithClassName(FileCheck2);
	iconWithClassName(FileClock);
	iconWithClassName(FileCode);
	iconWithClassName(FileCode2);
	iconWithClassName(FileCog);
	iconWithClassName(FileDiff);
	iconWithClassName(FileDigit);
	iconWithClassName(FileDown);
	iconWithClassName(FileHeart);
	iconWithClassName(FileImage);
	iconWithClassName(FileInput);
	iconWithClassName(FileJson);
	iconWithClassName(FileJson2);
	iconWithClassName(FileKey);
	iconWithClassName(FileKey2);
	iconWithClassName(FileLock);
	iconWithClassName(FileLock2);
	iconWithClassName(FileMinus);
	iconWithClassName(FileMinus2);
	iconWithClassName(FileMusic);
	iconWithClassName(FileOutput);
	iconWithClassName(FilePen);
	iconWithClassName(FilePenLine);
	iconWithClassName(FilePlus);
	iconWithClassName(FilePlus2);
	iconWithClassName(FileQuestion);
	iconWithClassName(FileScan);
	iconWithClassName(FileSearch);
	iconWithClassName(FileSearch2);
	iconWithClassName(FileSliders);
	iconWithClassName(FileSpreadsheet);
	iconWithClassName(FileStack);
	iconWithClassName(FileSymlink);
	iconWithClassName(FileTerminal);
	iconWithClassName(FileText);
	iconWithClassName(FileType);
	iconWithClassName(FileType2);
	iconWithClassName(FileUp);
	iconWithClassName(FileUser);
	iconWithClassName(FileVideo);
	iconWithClassName(FileVideo2);
	iconWithClassName(FileVolume);
	iconWithClassName(FileVolume2);
	iconWithClassName(FileWarning);
	iconWithClassName(FileX);
	iconWithClassName(FileX2);
	iconWithClassName(Files);
	iconWithClassName(Film);
	iconWithClassName(Filter);
	iconWithClassName(FilterX);
	iconWithClassName(Fingerprint);
	iconWithClassName(FireExtinguisher);
	iconWithClassName(Fish);
	iconWithClassName(FishOff);
	iconWithClassName(FishSymbol);
	iconWithClassName(Flag);
	iconWithClassName(FlagOff);
	iconWithClassName(FlagTriangleLeft);
	iconWithClassName(FlagTriangleRight);
	iconWithClassName(Flame);
	iconWithClassName(FlameKindling);
	iconWithClassName(Flashlight);
	iconWithClassName(FlashlightOff);
	iconWithClassName(FlaskConical);
	iconWithClassName(FlaskConicalOff);
	iconWithClassName(FlaskRound);
	iconWithClassName(FlipHorizontal);
	iconWithClassName(FlipHorizontal2);
	iconWithClassName(FlipVertical);
	iconWithClassName(FlipVertical2);
	iconWithClassName(Flower);
	iconWithClassName(Flower2);
	iconWithClassName(Focus);
	iconWithClassName(FoldHorizontal);
	iconWithClassName(FoldVertical);
	iconWithClassName(Folder);
	iconWithClassName(FolderArchive);
	iconWithClassName(FolderCheck);
	iconWithClassName(FolderClock);
	iconWithClassName(FolderClosed);
	iconWithClassName(FolderCode);
	iconWithClassName(FolderCog);
	iconWithClassName(FolderDot);
	iconWithClassName(FolderDown);
	iconWithClassName(FolderGit);
	iconWithClassName(FolderGit2);
	iconWithClassName(FolderHeart);
	iconWithClassName(FolderInput);
	iconWithClassName(FolderKanban);
	iconWithClassName(FolderKey);
	iconWithClassName(FolderLock);
	iconWithClassName(FolderMinus);
	iconWithClassName(FolderOpen);
	iconWithClassName(FolderOpenDot);
	iconWithClassName(FolderOutput);
	iconWithClassName(FolderPen);
	iconWithClassName(FolderPlus);
	iconWithClassName(FolderRoot);
	iconWithClassName(FolderSearch);
	iconWithClassName(FolderSearch2);
	iconWithClassName(FolderSymlink);
	iconWithClassName(FolderSync);
	iconWithClassName(FolderTree);
	iconWithClassName(FolderUp);
	iconWithClassName(FolderX);
	iconWithClassName(Folders);
	iconWithClassName(Footprints);
	iconWithClassName(Forklift);
	iconWithClassName(Forward);
	iconWithClassName(Frame);
	iconWithClassName(Framer);
	iconWithClassName(Frown);
	iconWithClassName(Fuel);
	iconWithClassName(Fullscreen);
	iconWithClassName(GalleryHorizontal);
	iconWithClassName(GalleryHorizontalEnd);
	iconWithClassName(GalleryThumbnails);
	iconWithClassName(GalleryVertical);
	iconWithClassName(GalleryVerticalEnd);
	iconWithClassName(Gamepad);
	iconWithClassName(Gamepad2);
	iconWithClassName(Gauge);
	iconWithClassName(Gavel);
	iconWithClassName(Gem);
	iconWithClassName(Ghost);
	iconWithClassName(Gift);
	iconWithClassName(GitBranch);
	iconWithClassName(GitBranchPlus);
	iconWithClassName(GitCommitHorizontal);
	iconWithClassName(GitCommitVertical);
	iconWithClassName(GitCompare);
	iconWithClassName(GitCompareArrows);
	iconWithClassName(GitFork);
	iconWithClassName(GitGraph);
	iconWithClassName(GitMerge);
	iconWithClassName(GitPullRequest);
	iconWithClassName(GitPullRequestArrow);
	iconWithClassName(GitPullRequestClosed);
	iconWithClassName(GitPullRequestCreate);
	iconWithClassName(GitPullRequestCreateArrow);
	iconWithClassName(GitPullRequestDraft);
	iconWithClassName(Github);
	iconWithClassName(Gitlab);
	iconWithClassName(GlassWater);
	iconWithClassName(Glasses);
	iconWithClassName(Globe);
	iconWithClassName(GlobeLock);
	iconWithClassName(Goal);
	iconWithClassName(Grab);
	iconWithClassName(GraduationCap);
	iconWithClassName(Grape);
	iconWithClassName(Grid2x2);
	iconWithClassName(Grid2x2Check);
	iconWithClassName(Grid2x2Plus);
	iconWithClassName(Grid2x2X);
	iconWithClassName(Grid3x3);
	iconWithClassName(Grip);
	iconWithClassName(GripHorizontal);
	iconWithClassName(GripVertical);
	iconWithClassName(Group);
	iconWithClassName(Guitar);
	iconWithClassName(Ham);
	iconWithClassName(Hammer);
	iconWithClassName(Hand);
	iconWithClassName(HandCoins);
	iconWithClassName(HandHeart);
	iconWithClassName(HandHelping);
	iconWithClassName(HandMetal);
	iconWithClassName(HandPlatter);
	iconWithClassName(Handshake);
	iconWithClassName(HardDrive);
	iconWithClassName(HardDriveDownload);
	iconWithClassName(HardDriveUpload);
	iconWithClassName(HardHat);
	iconWithClassName(Hash);
	iconWithClassName(Haze);
	iconWithClassName(HdmiPort);
	iconWithClassName(Heading);
	iconWithClassName(Heading1);
	iconWithClassName(Heading2);
	iconWithClassName(Heading3);
	iconWithClassName(Heading4);
	iconWithClassName(Heading5);
	iconWithClassName(Heading6);
	iconWithClassName(HeadphoneOff);
	iconWithClassName(Headphones);
	iconWithClassName(Headset);
	iconWithClassName(Heart);
	iconWithClassName(HeartCrack);
	iconWithClassName(HeartHandshake);
	iconWithClassName(HeartOff);
	iconWithClassName(HeartPulse);
	iconWithClassName(Heater);
	iconWithClassName(Hexagon);
	iconWithClassName(Highlighter);
	iconWithClassName(History);
	iconWithClassName(Hop);
	iconWithClassName(HopOff);
	iconWithClassName(Hospital);
	iconWithClassName(Hotel);
	iconWithClassName(Hourglass);
	iconWithClassName(House);
	iconWithClassName(HousePlug);
	iconWithClassName(HousePlus);
	iconWithClassName(HouseWifi);
	iconWithClassName(IceCreamBowl);
	iconWithClassName(IceCreamCone);
	iconWithClassName(IdCard);
	iconWithClassName(Image);
	iconWithClassName(ImageDown);
	iconWithClassName(ImageMinus);
	iconWithClassName(ImageOff);
	iconWithClassName(ImagePlay);
	iconWithClassName(ImagePlus);
	iconWithClassName(ImageUp);
	iconWithClassName(ImageUpscale);
	iconWithClassName(Images);
	iconWithClassName(Import);
	iconWithClassName(Inbox);
	iconWithClassName(IndentDecrease);
	iconWithClassName(IndentIncrease);
	iconWithClassName(IndianRupee);
	iconWithClassName(Infinity);
	iconWithClassName(Info);
	iconWithClassName(InspectionPanel);
	iconWithClassName(Instagram);
	iconWithClassName(Italic);
	iconWithClassName(IterationCcw);
	iconWithClassName(IterationCw);
	iconWithClassName(JapaneseYen);
	iconWithClassName(Joystick);
	iconWithClassName(Kanban);
	iconWithClassName(Key);
	iconWithClassName(KeyRound);
	iconWithClassName(KeySquare);
	iconWithClassName(Keyboard);
	iconWithClassName(KeyboardMusic);
	iconWithClassName(KeyboardOff);
	iconWithClassName(Lamp);
	iconWithClassName(LampCeiling);
	iconWithClassName(LampDesk);
	iconWithClassName(LampFloor);
	iconWithClassName(LampWallDown);
	iconWithClassName(LampWallUp);
	iconWithClassName(LandPlot);
	iconWithClassName(Landmark);
	iconWithClassName(Languages);
	iconWithClassName(Laptop);
	iconWithClassName(LaptopMinimal);
	iconWithClassName(LaptopMinimalCheck);
	iconWithClassName(Lasso);
	iconWithClassName(LassoSelect);
	iconWithClassName(Laugh);
	iconWithClassName(Layers);
	iconWithClassName(Layers2);
	iconWithClassName(LayoutDashboard);
	iconWithClassName(LayoutGrid);
	iconWithClassName(LayoutList);
	iconWithClassName(LayoutPanelLeft);
	iconWithClassName(LayoutPanelTop);
	iconWithClassName(LayoutTemplate);
	iconWithClassName(Leaf);
	iconWithClassName(LeafyGreen);
	iconWithClassName(Lectern);
	iconWithClassName(LetterText);
	iconWithClassName(Library);
	iconWithClassName(LibraryBig);
	iconWithClassName(LifeBuoy);
	iconWithClassName(Ligature);
	iconWithClassName(Lightbulb);
	iconWithClassName(LightbulbOff);
	iconWithClassName(Link);
	iconWithClassName(Link2);
	iconWithClassName(Link2Off);
	iconWithClassName(Linkedin);
	iconWithClassName(List);
	iconWithClassName(ListCheck);
	iconWithClassName(ListChecks);
	iconWithClassName(ListCollapse);
	iconWithClassName(ListEnd);
	iconWithClassName(ListFilter);
	iconWithClassName(ListFilterPlus);
	iconWithClassName(ListMinus);
	iconWithClassName(ListMusic);
	iconWithClassName(ListOrdered);
	iconWithClassName(ListPlus);
	iconWithClassName(ListRestart);
	iconWithClassName(ListStart);
	iconWithClassName(ListTodo);
	iconWithClassName(ListTree);
	iconWithClassName(ListVideo);
	iconWithClassName(ListX);
	iconWithClassName(Loader);
	iconWithClassName(LoaderCircle);
	iconWithClassName(LoaderPinwheel);
	iconWithClassName(Locate);
	iconWithClassName(LocateFixed);
	iconWithClassName(LocateOff);
	iconWithClassName(Lock);
	iconWithClassName(LockKeyhole);
	iconWithClassName(LockKeyholeOpen);
	iconWithClassName(LockOpen);
	iconWithClassName(LogIn);
	iconWithClassName(LogOut);
	iconWithClassName(Logs);
	iconWithClassName(Lollipop);
	iconWithClassName(Luggage);
	iconWithClassName(Magnet);
	iconWithClassName(Mail);
	iconWithClassName(MailCheck);
	iconWithClassName(MailMinus);
	iconWithClassName(MailOpen);
	iconWithClassName(MailPlus);
	iconWithClassName(MailQuestion);
	iconWithClassName(MailSearch);
	iconWithClassName(MailWarning);
	iconWithClassName(MailX);
	iconWithClassName(Mailbox);
	iconWithClassName(Mails);
	iconWithClassName(Map);
	iconWithClassName(MapPin);
	iconWithClassName(MapPinCheck);
	iconWithClassName(MapPinCheckInside);
	iconWithClassName(MapPinHouse);
	iconWithClassName(MapPinMinus);
	iconWithClassName(MapPinMinusInside);
	iconWithClassName(MapPinOff);
	iconWithClassName(MapPinPlus);
	iconWithClassName(MapPinPlusInside);
	iconWithClassName(MapPinX);
	iconWithClassName(MapPinXInside);
	iconWithClassName(MapPinned);
	iconWithClassName(MapPlus);
	iconWithClassName(Mars);
	iconWithClassName(MarsStroke);
	iconWithClassName(Martini);
	iconWithClassName(Maximize);
	iconWithClassName(Maximize2);
	iconWithClassName(Medal);
	iconWithClassName(Megaphone);
	iconWithClassName(MegaphoneOff);
	iconWithClassName(Meh);
	iconWithClassName(MemoryStick);
	iconWithClassName(Menu);
	iconWithClassName(Merge);
	iconWithClassName(MessageCircle);
	iconWithClassName(MessageCircleCode);
	iconWithClassName(MessageCircleDashed);
	iconWithClassName(MessageCircleHeart);
	iconWithClassName(MessageCircleMore);
	iconWithClassName(MessageCircleOff);
	iconWithClassName(MessageCirclePlus);
	iconWithClassName(MessageCircleQuestion);
	iconWithClassName(MessageCircleReply);
	iconWithClassName(MessageCircleWarning);
	iconWithClassName(MessageCircleX);
	iconWithClassName(MessageSquare);
	iconWithClassName(MessageSquareCode);
	iconWithClassName(MessageSquareDashed);
	iconWithClassName(MessageSquareDiff);
	iconWithClassName(MessageSquareDot);
	iconWithClassName(MessageSquareHeart);
	iconWithClassName(MessageSquareLock);
	iconWithClassName(MessageSquareMore);
	iconWithClassName(MessageSquareOff);
	iconWithClassName(MessageSquarePlus);
	iconWithClassName(MessageSquareQuote);
	iconWithClassName(MessageSquareReply);
	iconWithClassName(MessageSquareShare);
	iconWithClassName(MessageSquareText);
	iconWithClassName(MessageSquareWarning);
	iconWithClassName(MessageSquareX);
	iconWithClassName(MessagesSquare);
	iconWithClassName(Mic);
	iconWithClassName(MicOff);
	iconWithClassName(MicVocal);
	iconWithClassName(Microchip);
	iconWithClassName(Microscope);
	iconWithClassName(Microwave);
	iconWithClassName(Milestone);
	iconWithClassName(Milk);
	iconWithClassName(MilkOff);
	iconWithClassName(Minimize);
	iconWithClassName(Minimize2);
	iconWithClassName(Minus);
	iconWithClassName(Monitor);
	iconWithClassName(MonitorCheck);
	iconWithClassName(MonitorCog);
	iconWithClassName(MonitorDot);
	iconWithClassName(MonitorDown);
	iconWithClassName(MonitorOff);
	iconWithClassName(MonitorPause);
	iconWithClassName(MonitorPlay);
	iconWithClassName(MonitorSmartphone);
	iconWithClassName(MonitorSpeaker);
	iconWithClassName(MonitorStop);
	iconWithClassName(MonitorUp);
	iconWithClassName(MonitorX);
	iconWithClassName(Moon);
	iconWithClassName(MoonStar);
	iconWithClassName(Mountain);
	iconWithClassName(MountainSnow);
	iconWithClassName(Mouse);
	iconWithClassName(MouseOff);
	iconWithClassName(MousePointer);
	iconWithClassName(MousePointer2);
	iconWithClassName(MousePointerBan);
	iconWithClassName(MousePointerClick);
	iconWithClassName(Move);
	iconWithClassName(Move3d);
	iconWithClassName(MoveDiagonal);
	iconWithClassName(MoveDiagonal2);
	iconWithClassName(MoveDown);
	iconWithClassName(MoveDownLeft);
	iconWithClassName(MoveDownRight);
	iconWithClassName(MoveHorizontal);
	iconWithClassName(MoveLeft);
	iconWithClassName(MoveRight);
	iconWithClassName(MoveUp);
	iconWithClassName(MoveUpLeft);
	iconWithClassName(MoveUpRight);
	iconWithClassName(MoveVertical);
	iconWithClassName(Music);
	iconWithClassName(Music2);
	iconWithClassName(Music3);
	iconWithClassName(Music4);
	iconWithClassName(Navigation);
	iconWithClassName(Navigation2);
	iconWithClassName(Navigation2Off);
	iconWithClassName(NavigationOff);
	iconWithClassName(Network);
	iconWithClassName(Newspaper);
	iconWithClassName(Nfc);
	iconWithClassName(NonBinary);
	iconWithClassName(Notebook);
	iconWithClassName(NotebookPen);
	iconWithClassName(NotebookTabs);
	iconWithClassName(NotebookText);
	iconWithClassName(NotepadText);
	iconWithClassName(NotepadTextDashed);
	iconWithClassName(Nut);
	iconWithClassName(NutOff);
	iconWithClassName(Octagon);
	iconWithClassName(OctagonAlert);
	iconWithClassName(OctagonMinus);
	iconWithClassName(OctagonPause);
	iconWithClassName(OctagonX);
	iconWithClassName(Omega);
	iconWithClassName(Option);
	iconWithClassName(Orbit);
	iconWithClassName(Origami);
	iconWithClassName(Package);
	iconWithClassName(Package2);
	iconWithClassName(PackageCheck);
	iconWithClassName(PackageMinus);
	iconWithClassName(PackageOpen);
	iconWithClassName(PackagePlus);
	iconWithClassName(PackageSearch);
	iconWithClassName(PackageX);
	iconWithClassName(PaintBucket);
	iconWithClassName(PaintRoller);
	iconWithClassName(Paintbrush);
	iconWithClassName(PaintbrushVertical);
	iconWithClassName(Palette);
	iconWithClassName(PanelBottom);
	iconWithClassName(PanelBottomClose);
	iconWithClassName(PanelBottomDashed);
	iconWithClassName(PanelBottomOpen);
	iconWithClassName(PanelLeft);
	iconWithClassName(PanelLeftClose);
	iconWithClassName(PanelLeftDashed);
	iconWithClassName(PanelLeftOpen);
	iconWithClassName(PanelRight);
	iconWithClassName(PanelRightClose);
	iconWithClassName(PanelRightDashed);
	iconWithClassName(PanelRightOpen);
	iconWithClassName(PanelTop);
	iconWithClassName(PanelTopClose);
	iconWithClassName(PanelTopDashed);
	iconWithClassName(PanelTopOpen);
	iconWithClassName(PanelsLeftBottom);
	iconWithClassName(PanelsRightBottom);
	iconWithClassName(PanelsTopLeft);
	iconWithClassName(Paperclip);
	iconWithClassName(Parentheses);
	iconWithClassName(ParkingMeter);
	iconWithClassName(PartyPopper);
	iconWithClassName(Pause);
	iconWithClassName(PawPrint);
	iconWithClassName(PcCase);
	iconWithClassName(Pen);
	iconWithClassName(PenLine);
	iconWithClassName(PenOff);
	iconWithClassName(PenTool);
	iconWithClassName(Pencil);
	iconWithClassName(PencilLine);
	iconWithClassName(PencilOff);
	iconWithClassName(PencilRuler);
	iconWithClassName(Pentagon);
	iconWithClassName(Percent);
	iconWithClassName(PersonStanding);
	iconWithClassName(PhilippinePeso);
	iconWithClassName(Phone);
	iconWithClassName(PhoneCall);
	iconWithClassName(PhoneForwarded);
	iconWithClassName(PhoneIncoming);
	iconWithClassName(PhoneMissed);
	iconWithClassName(PhoneOff);
	iconWithClassName(PhoneOutgoing);
	iconWithClassName(Pi);
	iconWithClassName(Piano);
	iconWithClassName(Pickaxe);
	iconWithClassName(PictureInPicture);
	iconWithClassName(PictureInPicture2);
	iconWithClassName(PiggyBank);
	iconWithClassName(Pilcrow);
	iconWithClassName(PilcrowLeft);
	iconWithClassName(PilcrowRight);
	iconWithClassName(Pill);
	iconWithClassName(PillBottle);
	iconWithClassName(Pin);
	iconWithClassName(PinOff);
	iconWithClassName(Pipette);
	iconWithClassName(Pizza);
	iconWithClassName(Plane);
	iconWithClassName(PlaneLanding);
	iconWithClassName(PlaneTakeoff);
	iconWithClassName(Play);
	iconWithClassName(Plug);
	iconWithClassName(Plug2);
	iconWithClassName(PlugZap);
	iconWithClassName(Plus);
	iconWithClassName(Pocket);
	iconWithClassName(PocketKnife);
	iconWithClassName(Podcast);
	iconWithClassName(Pointer);
	iconWithClassName(PointerOff);
	iconWithClassName(Popcorn);
	iconWithClassName(Popsicle);
	iconWithClassName(PoundSterling);
	iconWithClassName(Power);
	iconWithClassName(PowerOff);
	iconWithClassName(Presentation);
	iconWithClassName(Printer);
	iconWithClassName(PrinterCheck);
	iconWithClassName(Projector);
	iconWithClassName(Proportions);
	iconWithClassName(Puzzle);
	iconWithClassName(Pyramid);
	iconWithClassName(QrCode);
	iconWithClassName(Quote);
	iconWithClassName(Rabbit);
	iconWithClassName(Radar);
	iconWithClassName(Radiation);
	iconWithClassName(Radical);
	iconWithClassName(Radio);
	iconWithClassName(RadioReceiver);
	iconWithClassName(RadioTower);
	iconWithClassName(Radius);
	iconWithClassName(RailSymbol);
	iconWithClassName(Rainbow);
	iconWithClassName(Rat);
	iconWithClassName(Ratio);
	iconWithClassName(Receipt);
	iconWithClassName(ReceiptCent);
	iconWithClassName(ReceiptEuro);
	iconWithClassName(ReceiptIndianRupee);
	iconWithClassName(ReceiptJapaneseYen);
	iconWithClassName(ReceiptPoundSterling);
	iconWithClassName(ReceiptRussianRuble);
	iconWithClassName(ReceiptSwissFranc);
	iconWithClassName(ReceiptText);
	iconWithClassName(RectangleEllipsis);
	iconWithClassName(RectangleHorizontal);
	iconWithClassName(RectangleVertical);
	iconWithClassName(Recycle);
	iconWithClassName(Redo);
	iconWithClassName(Redo2);
	iconWithClassName(RedoDot);
	iconWithClassName(RefreshCcw);
	iconWithClassName(RefreshCcwDot);
	iconWithClassName(RefreshCw);
	iconWithClassName(RefreshCwOff);
	iconWithClassName(Refrigerator);
	iconWithClassName(Regex);
	iconWithClassName(RemoveFormatting);
	iconWithClassName(Repeat);
	iconWithClassName(Repeat1);
	iconWithClassName(Repeat2);
	iconWithClassName(Replace);
	iconWithClassName(ReplaceAll);
	iconWithClassName(Reply);
	iconWithClassName(ReplyAll);
	iconWithClassName(Rewind);
	iconWithClassName(Ribbon);
	iconWithClassName(Rocket);
	iconWithClassName(RockingChair);
	iconWithClassName(RollerCoaster);
	iconWithClassName(Rotate3d);
	iconWithClassName(RotateCcw);
	iconWithClassName(RotateCcwSquare);
	iconWithClassName(RotateCw);
	iconWithClassName(RotateCwSquare);
	iconWithClassName(Route);
	iconWithClassName(RouteOff);
	iconWithClassName(Router);
	iconWithClassName(Rows2);
	iconWithClassName(Rows3);
	iconWithClassName(Rows4);
	iconWithClassName(Rss);
	iconWithClassName(Ruler);
	iconWithClassName(RussianRuble);
	iconWithClassName(Sailboat);
	iconWithClassName(Salad);
	iconWithClassName(Sandwich);
	iconWithClassName(Satellite);
	iconWithClassName(SatelliteDish);
	iconWithClassName(SaudiRiyal);
	iconWithClassName(Save);
	iconWithClassName(SaveAll);
	iconWithClassName(SaveOff);
	iconWithClassName(Scale);
	iconWithClassName(Scale3d);
	iconWithClassName(Scaling);
	iconWithClassName(Scan);
	iconWithClassName(ScanBarcode);
	iconWithClassName(ScanEye);
	iconWithClassName(ScanFace);
	iconWithClassName(ScanHeart);
	iconWithClassName(ScanLine);
	iconWithClassName(ScanQrCode);
	iconWithClassName(ScanSearch);
	iconWithClassName(ScanText);
	iconWithClassName(School);
	iconWithClassName(Scissors);
	iconWithClassName(ScissorsLineDashed);
	iconWithClassName(ScreenShare);
	iconWithClassName(ScreenShareOff);
	iconWithClassName(Scroll);
	iconWithClassName(ScrollText);
	iconWithClassName(Search);
	iconWithClassName(SearchCheck);
	iconWithClassName(SearchCode);
	iconWithClassName(SearchSlash);
	iconWithClassName(SearchX);
	iconWithClassName(Section);
	iconWithClassName(Send);
	iconWithClassName(SendHorizontal);
	iconWithClassName(SendToBack);
	iconWithClassName(SeparatorHorizontal);
	iconWithClassName(SeparatorVertical);
	iconWithClassName(Server);
	iconWithClassName(ServerCog);
	iconWithClassName(ServerCrash);
	iconWithClassName(ServerOff);
	iconWithClassName(Settings);
	iconWithClassName(Settings2);
	iconWithClassName(Shapes);
	iconWithClassName(Share);
	iconWithClassName(Share2);
	iconWithClassName(Sheet);
	iconWithClassName(Shell);
	iconWithClassName(Shield);
	iconWithClassName(ShieldAlert);
	iconWithClassName(ShieldBan);
	iconWithClassName(ShieldCheck);
	iconWithClassName(ShieldEllipsis);
	iconWithClassName(ShieldHalf);
	iconWithClassName(ShieldMinus);
	iconWithClassName(ShieldOff);
	iconWithClassName(ShieldPlus);
	iconWithClassName(ShieldQuestion);
	iconWithClassName(ShieldUser);
	iconWithClassName(ShieldX);
	iconWithClassName(Ship);
	iconWithClassName(ShipWheel);
	iconWithClassName(Shirt);
	iconWithClassName(ShoppingBag);
	iconWithClassName(ShoppingBasket);
	iconWithClassName(ShoppingCart);
	iconWithClassName(Shovel);
	iconWithClassName(ShowerHead);
	iconWithClassName(Shrimp);
	iconWithClassName(Shrink);
	iconWithClassName(Shrub);
	iconWithClassName(Shuffle);
	iconWithClassName(Sigma);
	iconWithClassName(Signal);
	iconWithClassName(SignalHigh);
	iconWithClassName(SignalLow);
	iconWithClassName(SignalMedium);
	iconWithClassName(SignalZero);
	iconWithClassName(Signature);
	iconWithClassName(Signpost);
	iconWithClassName(SignpostBig);
	iconWithClassName(Siren);
	iconWithClassName(SkipBack);
	iconWithClassName(SkipForward);
	iconWithClassName(Skull);
	iconWithClassName(Slack);
	iconWithClassName(Slash);
	iconWithClassName(Slice);
	iconWithClassName(SlidersHorizontal);
	iconWithClassName(SlidersVertical);
	iconWithClassName(Smartphone);
	iconWithClassName(SmartphoneCharging);
	iconWithClassName(SmartphoneNfc);
	iconWithClassName(Smile);
	iconWithClassName(SmilePlus);
	iconWithClassName(Snail);
	iconWithClassName(Snowflake);
	iconWithClassName(Sofa);
	iconWithClassName(Soup);
	iconWithClassName(Space);
	iconWithClassName(Spade);
	iconWithClassName(Sparkle);
	iconWithClassName(Sparkles);
	iconWithClassName(Speaker);
	iconWithClassName(Speech);
	iconWithClassName(SpellCheck);
	iconWithClassName(SpellCheck2);
	iconWithClassName(Spline);
	iconWithClassName(Split);
	iconWithClassName(SprayCan);
	iconWithClassName(Sprout);
	iconWithClassName(Square);
	iconWithClassName(SquareActivity);
	iconWithClassName(SquareArrowDown);
	iconWithClassName(SquareArrowDownLeft);
	iconWithClassName(SquareArrowDownRight);
	iconWithClassName(SquareArrowLeft);
	iconWithClassName(SquareArrowOutDownLeft);
	iconWithClassName(SquareArrowOutDownRight);
	iconWithClassName(SquareArrowOutUpLeft);
	iconWithClassName(SquareArrowOutUpRight);
	iconWithClassName(SquareArrowRight);
	iconWithClassName(SquareArrowUp);
	iconWithClassName(SquareArrowUpLeft);
	iconWithClassName(SquareArrowUpRight);
	iconWithClassName(SquareAsterisk);
	iconWithClassName(SquareBottomDashedScissors);
	iconWithClassName(SquareChartGantt);
	iconWithClassName(SquareCheck);
	iconWithClassName(SquareCheckBig);
	iconWithClassName(SquareChevronDown);
	iconWithClassName(SquareChevronLeft);
	iconWithClassName(SquareChevronRight);
	iconWithClassName(SquareChevronUp);
	iconWithClassName(SquareCode);
	iconWithClassName(SquareDashed);
	iconWithClassName(SquareDashedBottom);
	iconWithClassName(SquareDashedBottomCode);
	iconWithClassName(SquareDashedKanban);
	iconWithClassName(SquareDashedMousePointer);
	iconWithClassName(SquareDivide);
	iconWithClassName(SquareDot);
	iconWithClassName(SquareEqual);
	iconWithClassName(SquareFunction);
	iconWithClassName(SquareKanban);
	iconWithClassName(SquareLibrary);
	iconWithClassName(SquareM);
	iconWithClassName(SquareMenu);
	iconWithClassName(SquareMinus);
	iconWithClassName(SquareMousePointer);
	iconWithClassName(SquareParking);
	iconWithClassName(SquareParkingOff);
	iconWithClassName(SquarePen);
	iconWithClassName(SquarePercent);
	iconWithClassName(SquarePi);
	iconWithClassName(SquarePilcrow);
	iconWithClassName(SquarePlay);
	iconWithClassName(SquarePlus);
	iconWithClassName(SquarePower);
	iconWithClassName(SquareRadical);
	iconWithClassName(SquareRoundCorner);
	iconWithClassName(SquareScissors);
	iconWithClassName(SquareSigma);
	iconWithClassName(SquareSlash);
	iconWithClassName(SquareSplitHorizontal);
	iconWithClassName(SquareSplitVertical);
	iconWithClassName(SquareSquare);
	iconWithClassName(SquareStack);
	iconWithClassName(SquareTerminal);
	iconWithClassName(SquareUser);
	iconWithClassName(SquareUserRound);
	iconWithClassName(SquareX);
	iconWithClassName(Squircle);
	iconWithClassName(Squirrel);
	iconWithClassName(Stamp);
	iconWithClassName(Star);
	iconWithClassName(StarHalf);
	iconWithClassName(StarOff);
	iconWithClassName(StepBack);
	iconWithClassName(StepForward);
	iconWithClassName(Stethoscope);
	iconWithClassName(Sticker);
	iconWithClassName(StickyNote);
	iconWithClassName(Store);
	iconWithClassName(StretchHorizontal);
	iconWithClassName(StretchVertical);
	iconWithClassName(Strikethrough);
	iconWithClassName(Subscript);
	iconWithClassName(Sun);
	iconWithClassName(SunDim);
	iconWithClassName(SunMedium);
	iconWithClassName(SunMoon);
	iconWithClassName(SunSnow);
	iconWithClassName(Sunrise);
	iconWithClassName(Sunset);
	iconWithClassName(Superscript);
	iconWithClassName(SwatchBook);
	iconWithClassName(SwissFranc);
	iconWithClassName(SwitchCamera);
	iconWithClassName(Sword);
	iconWithClassName(Swords);
	iconWithClassName(Syringe);
	iconWithClassName(Table);
	iconWithClassName(Table2);
	iconWithClassName(TableCellsMerge);
	iconWithClassName(TableCellsSplit);
	iconWithClassName(TableColumnsSplit);
	iconWithClassName(TableOfContents);
	iconWithClassName(TableProperties);
	iconWithClassName(TableRowsSplit);
	iconWithClassName(Tablet);
	iconWithClassName(TabletSmartphone);
	iconWithClassName(Tablets);
	iconWithClassName(Tag);
	iconWithClassName(Tags);
	iconWithClassName(Tally1);
	iconWithClassName(Tally2);
	iconWithClassName(Tally3);
	iconWithClassName(Tally4);
	iconWithClassName(Tally5);
	iconWithClassName(Tangent);
	iconWithClassName(Target);
	iconWithClassName(Telescope);
	iconWithClassName(Tent);
	iconWithClassName(TentTree);
	iconWithClassName(Terminal);
	iconWithClassName(TestTube);
	iconWithClassName(TestTubeDiagonal);
	iconWithClassName(TestTubes);
	iconWithClassName(Text);
	iconWithClassName(TextCursor);
	iconWithClassName(TextCursorInput);
	iconWithClassName(TextQuote);
	iconWithClassName(TextSearch);
	iconWithClassName(TextSelect);
	iconWithClassName(Theater);
	iconWithClassName(Thermometer);
	iconWithClassName(ThermometerSnowflake);
	iconWithClassName(ThermometerSun);
	iconWithClassName(ThumbsDown);
	iconWithClassName(ThumbsUp);
	iconWithClassName(Ticket);
	iconWithClassName(TicketCheck);
	iconWithClassName(TicketMinus);
	iconWithClassName(TicketPercent);
	iconWithClassName(TicketPlus);
	iconWithClassName(TicketSlash);
	iconWithClassName(TicketX);
	iconWithClassName(Tickets);
	iconWithClassName(TicketsPlane);
	iconWithClassName(Timer);
	iconWithClassName(TimerOff);
	iconWithClassName(TimerReset);
	iconWithClassName(ToggleLeft);
	iconWithClassName(ToggleRight);
	iconWithClassName(Toilet);
	iconWithClassName(Tornado);
	iconWithClassName(Torus);
	iconWithClassName(Touchpad);
	iconWithClassName(TouchpadOff);
	iconWithClassName(TowerControl);
	iconWithClassName(ToyBrick);
	iconWithClassName(Tractor);
	iconWithClassName(TrafficCone);
	iconWithClassName(TrainFront);
	iconWithClassName(TrainFrontTunnel);
	iconWithClassName(TrainTrack);
	iconWithClassName(TramFront);
	iconWithClassName(Transgender);
	iconWithClassName(Trash);
	iconWithClassName(Trash2);
	iconWithClassName(TreeDeciduous);
	iconWithClassName(TreePalm);
	iconWithClassName(TreePine);
	iconWithClassName(Trees);
	iconWithClassName(Trello);
	iconWithClassName(TrendingDown);
	iconWithClassName(TrendingUp);
	iconWithClassName(TrendingUpDown);
	iconWithClassName(Triangle);
	iconWithClassName(TriangleAlert);
	iconWithClassName(TriangleDashed);
	iconWithClassName(TriangleRight);
	iconWithClassName(Trophy);
	iconWithClassName(Truck);
	iconWithClassName(Turtle);
	iconWithClassName(Tv);
	iconWithClassName(TvMinimal);
	iconWithClassName(TvMinimalPlay);
	iconWithClassName(Twitch);
	iconWithClassName(Twitter);
	iconWithClassName(Type);
	iconWithClassName(TypeOutline);
	iconWithClassName(Umbrella);
	iconWithClassName(UmbrellaOff);
	iconWithClassName(Underline);
	iconWithClassName(Undo);
	iconWithClassName(Undo2);
	iconWithClassName(UndoDot);
	iconWithClassName(UnfoldHorizontal);
	iconWithClassName(UnfoldVertical);
	iconWithClassName(Ungroup);
	iconWithClassName(University);
	iconWithClassName(Unlink);
	iconWithClassName(Unlink2);
	iconWithClassName(Unplug);
	iconWithClassName(Upload);
	iconWithClassName(Usb);
	iconWithClassName(User);
	iconWithClassName(UserCheck);
	iconWithClassName(UserCog);
	iconWithClassName(UserMinus);
	iconWithClassName(UserPen);
	iconWithClassName(UserPlus);
	iconWithClassName(UserRound);
	iconWithClassName(UserRoundCheck);
	iconWithClassName(UserRoundCog);
	iconWithClassName(UserRoundMinus);
	iconWithClassName(UserRoundPen);
	iconWithClassName(UserRoundPlus);
	iconWithClassName(UserRoundSearch);
	iconWithClassName(UserRoundX);
	iconWithClassName(UserSearch);
	iconWithClassName(UserX);
	iconWithClassName(Users);
	iconWithClassName(UsersRound);
	iconWithClassName(Utensils);
	iconWithClassName(UtensilsCrossed);
	iconWithClassName(UtilityPole);
	iconWithClassName(Variable);
	iconWithClassName(Vault);
	iconWithClassName(Vegan);
	iconWithClassName(VenetianMask);
	iconWithClassName(Venus);
	iconWithClassName(VenusAndMars);
	iconWithClassName(Vibrate);
	iconWithClassName(VibrateOff);
	iconWithClassName(Video);
	iconWithClassName(VideoOff);
	iconWithClassName(Videotape);
	iconWithClassName(View);
	iconWithClassName(Voicemail);
	iconWithClassName(Volleyball);
	iconWithClassName(Volume);
	iconWithClassName(Volume1);
	iconWithClassName(Volume2);
	iconWithClassName(VolumeOff);
	iconWithClassName(VolumeX);
	iconWithClassName(Vote);
	iconWithClassName(Wallet);
	iconWithClassName(WalletCards);
	iconWithClassName(WalletMinimal);
	iconWithClassName(Wallpaper);
	iconWithClassName(Wand);
	iconWithClassName(WandSparkles);
	iconWithClassName(Warehouse);
	iconWithClassName(WashingMachine);
	iconWithClassName(Watch);
	iconWithClassName(Waves);
	iconWithClassName(WavesLadder);
	iconWithClassName(Waypoints);
	iconWithClassName(Webcam);
	iconWithClassName(Webhook);
	iconWithClassName(WebhookOff);
	iconWithClassName(Weight);
	iconWithClassName(Wheat);
	iconWithClassName(WheatOff);
	iconWithClassName(WholeWord);
	iconWithClassName(Wifi);
	iconWithClassName(WifiHigh);
	iconWithClassName(WifiLow);
	iconWithClassName(WifiOff);
	iconWithClassName(WifiZero);
	iconWithClassName(Wind);
	iconWithClassName(WindArrowDown);
	iconWithClassName(Wine);
	iconWithClassName(WineOff);
	iconWithClassName(Workflow);
	iconWithClassName(Worm);
	iconWithClassName(WrapText);
	iconWithClassName(Wrench);
	iconWithClassName(X);
	iconWithClassName(Youtube);
	iconWithClassName(Zap);
	iconWithClassName(ZapOff);
	iconWithClassName(ZoomIn);
	iconWithClassName(ZoomOut);
}
